-- CreateTable
CREATE TABLE "ProcedurePrice" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "priceCents" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ProcedurePrice_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ProcedurePrice_name_key" ON "ProcedurePrice"("name");

-- CreateTable
CREATE TABLE "ProductCatalog" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "use" TEXT NOT NULL,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "unitPriceCents" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ProductCatalog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ProductCatalog_name_key" ON "ProductCatalog"("name");

-- CreateTable
CREATE TABLE "TicketRecord" (
    "id" TEXT NOT NULL,
    "ticketNumber" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateISO" TEXT NOT NULL,
    "appointmentId" TEXT,
    "patientId" TEXT NOT NULL,
    "patientName" TEXT NOT NULL,
    "patientDni" TEXT NOT NULL,
    "procedureName" TEXT NOT NULL,
    "procedureUnitPriceCents" INTEGER NOT NULL,
    "paymentEfectivoCents" INTEGER NOT NULL DEFAULT 0,
    "paymentYapeCents" INTEGER NOT NULL DEFAULT 0,
    "paymentPlinCents" INTEGER NOT NULL DEFAULT 0,
    "paymentTransferenciaCents" INTEGER NOT NULL DEFAULT 0,
    "paymentTotalCents" INTEGER NOT NULL DEFAULT 0,
    "totalCents" INTEGER NOT NULL,
    CONSTRAINT "TicketRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TicketRecord_ticketNumber_key" ON "TicketRecord"("ticketNumber");
-- CreateIndex
CREATE UNIQUE INDEX "TicketRecord_appointmentId_key" ON "TicketRecord"("appointmentId");

-- CreateTable
CREATE TABLE "TicketLine" (
    "id" SERIAL NOT NULL,
    "ticketId" TEXT NOT NULL,
    "productId" INTEGER,
    "name" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unitPriceCents" INTEGER NOT NULL,
    "lineTotalCents" INTEGER NOT NULL,
    CONSTRAINT "TicketLine_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TicketLine_ticketId_idx" ON "TicketLine"("ticketId");

-- AddForeignKey
ALTER TABLE "TicketRecord" ADD CONSTRAINT "TicketRecord_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TicketRecord" ADD CONSTRAINT "TicketRecord_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TicketLine" ADD CONSTRAINT "TicketLine_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "TicketRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TicketLine" ADD CONSTRAINT "TicketLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductCatalog"("id") ON DELETE SET NULL ON UPDATE CASCADE;

